const fs = require("fs");
const path = require("path");

const SPLITS = ["train", "val", "test"];

function parseArgs(argv) {
  const args = {
    input: path.resolve(__dirname, "..", "data_splits", "ezzayra_oliviers_geojson"),
    output: path.resolve(__dirname, "..", "earth_engine", "export_sentinel2_l2a_may_june.js"),
    year: 2025,
    maxCloudPercent: 60,
    scale: 10,
    driveFolder: "ezzayra_sentinel2_l2a_2025_05_06",
  };

  for (let i = 2; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--input") args.input = path.resolve(argv[++i]);
    else if (arg === "--output") args.output = path.resolve(argv[++i]);
    else if (arg === "--year") args.year = Number(argv[++i]);
    else if (arg === "--max-cloud-percent") args.maxCloudPercent = Number(argv[++i]);
    else if (arg === "--scale") args.scale = Number(argv[++i]);
    else if (arg === "--drive-folder") args.driveFolder = argv[++i];
    else if (arg === "--help") {
      console.log("Usage: node scripts/generate_gee_sentinel2_export.js [--year 2025] [--input DIR] [--output FILE]");
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  if (!Number.isInteger(args.year)) throw new Error("--year must be an integer");
  return args;
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function makeFeaturePayload(inputDir) {
  return SPLITS.flatMap((split) => {
    const geojson = readJson(path.join(inputDir, `${split}.geojson`));
    return geojson.features.map((feature) => ({
      type: "Feature",
      id: feature.id,
      properties: {
        id: feature.properties.id,
        split: feature.properties.split,
        cultivation_system: feature.properties.cultivation_system,
        governorate: feature.properties.governorate,
        zone_id: feature.properties.zone_id,
        area_ha: feature.properties.area_ha,
      },
      geometry: feature.geometry,
    }));
  });
}

function buildGeeScript(features, args) {
  const startDate = `${args.year}-05-01`;
  const endDate = `${args.year}-06-30`;
  const payload = JSON.stringify(features, null, 2);

  return `// Generated by scripts/generate_gee_sentinel2_export.js
// Goal: Sentinel-2 L2A May-June composites for EZZAYRA olive parcel splits.
//
// How to use:
// 1. Open https://code.earthengine.google.com/
// 2. Paste this file in a new script.
// 3. Run it.
// 4. In the Tasks tab, launch the exports you need.
//
// Output bands per GeoTIFF:
// B02, B03, B04, B08, B11

var START_DATE = '${startDate}';
var END_DATE = '${endDate}';
var MAX_CLOUD_PERCENT = ${args.maxCloudPercent};
var EXPORT_SCALE_METERS = ${args.scale};
var DRIVE_FOLDER = '${args.driveFolder}';
var BANDS = ['B2', 'B3', 'B4', 'B8', 'B11'];

var rawFeatures = ${payload};

function toEeFeature(rawFeature) {
  return ee.Feature(
    ee.Geometry(rawFeature.geometry),
    rawFeature.properties
  );
}

var parcels = ee.FeatureCollection(rawFeatures.map(toEeFeature));
Map.centerObject(parcels, 7);
Map.addLayer(parcels, {}, 'EZZAYRA parcels');

function maskWithScl(image) {
  var scl = image.select('SCL');

  // Keep useful olive/soil contrast pixels:
  // 4 = vegetation, 5 = bare soil.
  var validMask = scl.eq(4).or(scl.eq(5));

  return image
    .select(BANDS)
    .updateMask(validMask)
    .copyProperties(image, image.propertyNames());
}

var s2 = ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
  .filterDate(START_DATE, END_DATE)
  .filterBounds(parcels.geometry())
  .filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', MAX_CLOUD_PERCENT))
  .map(maskWithScl);

var composite = s2.median().rename(['B02', 'B03', 'B04', 'B08', 'B11']);

Map.addLayer(
  composite.select(['B04', 'B03', 'B02']),
  {min: 0, max: 3000},
  'Sentinel-2 RGB median SCL masked'
);

print('Parcels', parcels.size());
print('Sentinel-2 images after filters', s2.size());
print('Date range', START_DATE, END_DATE);

rawFeatures.forEach(function(rawFeature) {
  var feature = toEeFeature(rawFeature);
  var props = rawFeature.properties;
  var parcelId = String(props.id).replace(/[^a-zA-Z0-9_\\-]/g, '_');
  var split = String(props.split).replace(/[^a-zA-Z0-9_\\-]/g, '_');
  var system = String(props.cultivation_system).replace(/[^a-zA-Z0-9_\\-]/g, '_');
  var exportName = [
    split,
    system,
    parcelId,
    '${args.year}',
    '05_06',
    's2_l2a'
  ].join('__');

  Export.image.toDrive({
    image: composite.clip(feature.geometry()),
    description: exportName,
    folder: DRIVE_FOLDER + '_' + split,
    fileNamePrefix: exportName,
    region: feature.geometry(),
    scale: EXPORT_SCALE_METERS,
    crs: 'EPSG:4326',
    maxPixels: 1e13,
    fileFormat: 'GeoTIFF'
  });
});
`;
}

function main() {
  const args = parseArgs(process.argv);
  const features = makeFeaturePayload(args.input);
  fs.mkdirSync(path.dirname(args.output), { recursive: true });
  fs.writeFileSync(args.output, buildGeeScript(features, args), "utf8");

  console.log(
    JSON.stringify(
      {
        output: args.output,
        feature_count: features.length,
        year: args.year,
        period: [`${args.year}-05-01`, `${args.year}-06-30`],
        bands: ["B02", "B03", "B04", "B08", "B11"],
        cloud_mask: "SCL in [4 vegetation, 5 bare soil]",
      },
      null,
      2,
    ),
  );
}

main();
